### ISSUE TITLE
Missing facilities

### ISSUE THREAD

**Issue by foundatron** [keum/KC_CSO_Status#6]
There are facilities listed in the [CSO Status csv](http://your.kingcounty.gov/dnrp/library/wastewater/cso/img/CSO.CSV) that not in https://github.com/keum/KC_CSO_Status/blob/master/cso_coord.csv. From what I can tell these are missing:
1. TEST.CSOSTATUS_N
2. KDOM.CSOSTATUS_N
3. DEXT.CSOSTATUS_N
4. DENL.CSOSTATUS_N
5. CONN.CSOSTATUS_N

**Comment by keum** [comment]
Only need to show all the list from cso_coord.csv so those status data *.CSOSTATUS_N is generated from plant server that spits out more than official list. So cso_coord.csv is the official list and only need to display them officially. Hope that makes sense. thanks for checking.
